spring:
  data:
    mongodb:
      database: myanimelist # Database name.
      host: localhost # Mongo server host. Cannot be set with URI.
      port: 27017 # Mongo server port. Cannot be set with URI.